### PR TITLE
Address `set-output` deprecation

### PR DESCRIPTION
**Pull request by NotMyFault**
https://github.com/jenkins-infra/helpdesk/issues/3176

### CODE REVIEW

**Review by dduportal — APPROVED** [review]

**Comment by smerle33** [comment]
@NotMyFault just a side note, i am not quite sure it worked as expected ... we are using it here for example : https://github.com/jenkins-infra/docker-jenkins-weekly/actions/runs/3994910744/jobs/6853165176
and while it seems to get the correct version : `jenkins_version=2.387 >> $GITHUB_OUTPUT`
the step right after doesn't get it  : ` FULL_VERSION=jenkins/jenkins:-${SUFFIX}` but should `FULL_VERSION=jenkins/jenkins:${{ steps.update.outputs.jenkins_version }}-${SUFFIX}`
maybe a mistake in using it but I don't see it

**Comment by garethjevans** [comment]
@dduportal a note on this - just printing the line to the output doesn't work here (https://github.com/jenkins-infra/jenkins-version/blob/a51ca8f0a6282a3255062b9b1fbc772d356b94b4/pkg/cmd/get.go#L114).  You need to pass in `$GITHUB_OUTPUT` as a file descriptor and append to that file

**Comment by dduportal** [comment]
Thanks @garethjevans , I was working on a fix, your message confirms my initial analysis. Thanks for the pointer!

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-version/pull/91

**Pull request merged**
